{{- if not .Values.secret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cavalry.secretName" . }}
  labels:
    {{- include "cavalry.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $k, $v := .Values.secret.keys }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}
