apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cavalry.fullname" . }}-worker
  labels:
    {{- include "cavalry.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cavalry.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "cavalry.labels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      containers:
        - name: worker
          image: {{ include "cavalry.image" (dict "root" . "component" .Values.worker) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- include "cavalry.envFromSecret" . | nindent 12 }}
            {{- include "cavalry.envFromConfig" . | nindent 12 }}
            {{- with .Values.worker.extraEnv }}
            {{- range $k, $v := . }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
            {{- end }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
